### PR TITLE
Added Dark/Light mode toggle button

### LINKED ISSUE #19: Dark mode toggle button
### What is this About?

Feature Request:
Addition of dark mode toggle button and storing the users preference in local storage so as to use the same theme that the user has set previously while loading the web app for the next time.

<br />

### Expected Behavior

The user would be able to toggle between different themes as per their preference
<br />

### Current Behavior

There is no such button

<br />

### Failure Information (for bugs)

<br />

### Steps to Reproduce

<br />

### Context

<br />

### PR DESCRIPTION
**Pull request by SubhamKarmakar24**
Closes #19 

## Proposed Changes

  - Addition of Dark mode toggle button
  - The preferred theme that the user has chosen is saved in cache. So, the next time the user opens the website, the preferred theme is already applied.
  - Maintains the Neumorphic theme of the website

### CODE REVIEW

**Comment by SubhamKarmakar24** [comment]
> 
> 
> Closes #19
> ## Proposed Changes
> 
>     * Addition of Dark mode toggle button
> 
>     * The preferred theme that the user has chosen is saved in cache. So, the next time the user opens the website, the preferred theme is already applied.
> 
>     * Maintains the Neumorphic theme of the website

@BraydenTW Can you please verify the PR?

**Review by BraydenTW — APPROVED** [review]
Lgtm!

**Comment by BraydenTW** [comment]
Hey @SubhamKarmakar24, could you change the styles so the background and elements have more contrast before? (Also keep the light mode theme the same as the original)

7602F147-4622-43BB-A90D-F1012BD2585D
 (I have reverted the PR)

**Comment by SubhamKarmakar24** [comment]
> 
> 
> Hey @SubhamKarmakar24, could you change the styles so the background and elements have more contrast before? (Also keep the light mode theme the same as the original)
> 
> 7602F147-4622-43BB-A90D-F1012BD2585D (I have reverted the PR)

I haven't actually changed the light mode. I am adding more contrast to them and will make a PR soon.

**Comment by BraydenTW** [comment]
Strange, this is what it looks like when you changed it:

IMG_0220

Anyways, no problem. Just make sure before you deploy that the colors for the light and dark them have a good enough contrast.

**Comment by SubhamKarmakar24** [comment]
Maybe I didn't pull the latest changes before making the PR. 
Anyway, I am making the requested changes and submitting another PR soon.
Thanks

**Pull request merged**
