### PR TITLE
Remove search prop passed to Results component - not being used

### PR DESCRIPTION
**Pull request by diogo405**

### CODE REVIEW

**Comment by BraydenTW** [comment]
Awesome work, thanks!

**Comment by diogo405** [comment]
> Awesome work, thanks!

Hey, I was thinking we could write some e2e tests with Cypress, what do you reckon?

**Comment by BraydenTW** [comment]
@diogo405, I’ve thinking about it but am not quite fluent with Cypress or other e2e testing tools.

Would it be a short enough task for you to do a PR on it or should we collaborate?

**Comment by diogo405** [comment]
> @diogo405, I’ve thinking about it but am not quite fluent with Cypress or other e2e testing tools.
> 
> Would it be a short enough task for you to do a PR on it or should we collaborate?

I think I can do with a PR. Initially I would do the tests for the search - maybe a "no results found" as well?!

**Comment by BraydenTW** [comment]
Yes, I think that would be great. Let me know if I can help :D

**Pull request merged**
