### PR TITLE
added debounce to search fixes-#22

### LINKED ISSUE #22: Debouce in search bar
### What is this About?

This is a feature regarding adding debounce in the search bar

<br />

### Expected Behavior

Search and filter the list only after a certain delay to reduce search renders

<br />

### Current Behavior

The searched list gets rendered every time a new character is added or deleted

<br />

### Failure Information (for bugs)

<br />

### Steps to Reproduce

<br />

### Context

<br />

### PR DESCRIPTION
**Pull request by pawankm21**
Fixes #22 

## Proposed Changes
  - Search and filter the list only after a certain delay to reduce search renders
  -
  -

### CODE REVIEW

**Review by BraydenTW — CHANGES_REQUESTED** [review]
Could we change the devounce time to half of what you have it right now?

It’s a great optimization, however I feel like I am waiting a lot.

**Comment by pawankm21** [comment]
Ok sure.

**Comment by pawankm21** [comment]
400ms should work fine.

**Review by BraydenTW — APPROVED** [review]

**Comment by BraydenTW** [comment]
Much better - thanks!

**Pull request merged**
