### PR TITLE
fix: first render UI

### PR DESCRIPTION
**Pull request by faran4engg**
Fixes #

Screenshot 2021-10-03 at 12 50 33 AM

### CODE REVIEW

**Comment by BraydenTW** [comment]
Thanks for the PR! However could we make the style consistent with the “No results” UI? I would prefer to have a static image with the same svg icon style as it. 

Also make the title instead say: “Please type keywords to search” with NO emojis and NO extra uppercases. 

Thank you!

**Comment by faran4engg** [comment]
> Thanks for the PR! However could we make the style consistent with the “No results” UI? I would prefer to have a static image with the same svg icon style as it.
> 
> Also make the title instead say: “Please type keywords to search” with NO emojis and NO extra uppercases.
> 
> Thank you!

Cool. Searching for svg 😃

**Comment by faran4engg** [comment]
> > Thanks for the PR! However could we make the style consistent with the “No results” UI? I would prefer to have a static image with the same svg icon style as it.
> > Also make the title instead say: “Please type keywords to search” with NO emojis and NO extra uppercases.
> > Thank you!
> 
> Cool. Searching for svg 😃

Done @BraydenTW

**Comment by BraydenTW** [comment]
Thanks, that should do for now.

**Comment by faran4engg** [comment]
> Thanks, that should do for now.

You're welcome. Could you kindly assign it to me and add the labels please. Thanks in advance :)

**Pull request merged**
