### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by diogo405**
Fixes e2e tests.

### CODE REVIEW

**Comment by BraydenTW** [comment]
Thanks again for being so helpful on this open source project. I’m not very familiar with the e2e tests so thank you so much for fixing them.

How does the initial search work now? I fixed the algorithm again. I’d love to hear your thoughts.

**Comment by BraydenTW** [comment]
@diogo405 , make sure you put this command in your terminal so when you push something to Github it will count you as a contributor on this repo :D

```sh
git config --global user.email "your_git_email@email.com"
```

**Comment by diogo405** [comment]
Ah didn't know that 😅 I'm such a n00bie on Github pull requests hehe

**Comment by BraydenTW** [comment]
No problem ;D

**Comment by diogo405** [comment]
> Thanks again for being so helpful on this open source project. I’m not very familiar with the e2e tests so thank you so much for fixing them.
> 
> How does the initial search work now? I fixed the algorithm again. I’d love to hear your thoughts.

No worries mate 👍🏽 I think we can still improve. For example if you search "ppy" it doesn't return any results and I think it should return results with the keyword "happy". That's happening because in the Container.js you have:

```
if (keyword.indexOf(query) === 0) {
```

Which only returns true if you match the beginning of the string. If you change to (below) it fixes the issue I believe:

```
if (keyword.indexOf(query) >= 0) {
```

I've submitted a PR with the fix :)

**Pull request merged**
